# DBサーバのホスト名（DBが動作しているサーバのIPアドレス）
host: "0.0.0.0"

# DBサーバのポート番号 (Postgresなら5432、MySQLなら3306が一般的)
port: 5432

# DBサーバのユーザ名
username: "user_name"

# DBサーバのパスワード
username: "pass"

# データベース名
database: "database_name"

# テーブルの定義（スキーマの代用、参考https://tech.griphone.co.jp/2020/12/14/table2yaml/）
# Float, Integer, BigInteger, Boolean, String, DateTimeから選択
table: 
  name: table_name
  dtype:
    -
      field: a
      type: Integer
    -
      field: b
      type: BigInteger
    -
      field: c
      type: DateTime
    -
      field: d
      type: Float
    -
      field: e
      type: Boolean
    -
      field: f
      type: Float
